# Generated by Django 4.2.6 on 2023-10-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img',
            field=models.ImageField(default=1, upload_to='images', verbose_name='Car image'),
            preserve_default=False,
        ),
    ]
